version: "2.1"

services:
    store:
        build:
            context: .
            dockerfile: ./dockerfiles/store/Dockerfile
        expose: 
            - "8000"
        ports:
            - "8000:8000"
    warehouse:
        build:
            context: .
            dockerfile: ./dockerfiles/warehouse/Dockerfile
        expose: 
            - "8001"
        ports:
            - "8001:8001"
    client:
        build:
            context: .
            dockerfile: ./dockerfiles/client/Dockerfile
        depends_on: 
            - store
            - warehouse